/* FISICO_MANURAR: */

CREATE DATABASE crud;
USE crud;

CREATE TABLE CLIENTE (
    CPFCNPJ VARCHAR(14) PRIMARY KEY,
    Nome VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Endereco VARCHAR(255) NOT NULL
);

CREATE TABLE FORNECEDOR (
    CNPJ VARCHAR(14) PRIMARY KEY,
    Nome VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Endereco VARCHAR(255) NOT NULL
);

CREATE TABLE USUARIO (
    ID INTEGER PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL
);

CREATE TABLE PRODUTO (
    ID INTEGER PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    PRECO_UNI FLOAT NOT NULL,
    QUT_ESTOQUE INTEGER,
    ID_FORNECEDOR VARCHAR(14) NOT NULL
   );

CREATE TABLE VENDA (
    NF INTEGER PRIMARY KEY,
    ID_CLIENTE VARCHAR(14),
    ID_USUARIO INTEGER,
    SUBTOTAL FLOAT,
    QUT_ITENS INTEGER
);

CREATE TABLE VENDA_PRODUTOS (
    ID INTEGER PRIMARY KEY,
    ID_COMPRA VARCHAR(44),
    ID_PRODUTO INTEGER,
    PRECO_UNIT FLOAT,
    QUANTIDADE INTEGER
);

CREATE TABLE COMPRA (
    NF VARCHAR(44) PRIMARY KEY,
    ID_FORNECEDOR VARCHAR(14),
    ID_USUARIO INTEGER,
    SUBTOTAL FLOAT,
    QUT_ITENS INTEGER
);

CREATE TABLE COMPRA_PRODUTOS (
    ID INTEGER PRIMARY KEY,
    ID_COMPRA VARCHAR(44),
    ID_PRODUTO INTEGER,
    PRECO_UNIT FLOAT,
    QUANTIDADE INTEGER
);
 
ALTER TABLE PRODUTO ADD CONSTRAINT FK_PRODUTO_1
    FOREIGN KEY (ID_FORNECEDOR)
    REFERENCES FORNECEDOR (CNPJ)
    ON DELETE CASCADE;
 
ALTER TABLE VENDA ADD CONSTRAINT FK_VENDA_2
    FOREIGN KEY (ID_CLIENTE)    
    REFERENCES CLIENTE (CPFCNPJ)
    ON DELETE CASCADE;
    
ALTER TABLE VENDA ADD CONSTRAINT FK_VENDA_3
    FOREIGN KEY (ID_USUARIO)		
    REFERENCES USUARIO (ID)
    ON DELETE CASCADE;
 
ALTER TABLE VENDA_PRODUTOS ADD CONSTRAINT FK_VENDA_PRODUTOS_1
    FOREIGN KEY (ID_PRODUTO)
    REFERENCES PRODUTO (ID)
    ON DELETE CASCADE;
    
ALTER TABLE VENDA_PRODUTOS ADD CONSTRAINT FK_VENDA_PRODUTOS_2
		FOREIGN KEY (ID_COMPRA)
        REFERENCES COMPRA (NF)
        ON DELETE CASCADE;
 
ALTER TABLE COMPRA ADD CONSTRAINT FK_COMPRA_2
    FOREIGN KEY (ID_FORNECEDOR)
    REFERENCES FORNECEDOR (CNPJ)
    ON DELETE CASCADE;
    
ALTER TABLE COMPRA ADD CONSTRAINT FK_COMPRA_3
	FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO (ID)
    ON DELETE CASCADE;
 
ALTER TABLE COMPRA_PRODUTOS ADD CONSTRAINT FK_COMPRA_PRODUTOS_1
    FOREIGN KEY (ID_PRODUTO)
    REFERENCES PRODUTO (ID)
    ON DELETE CASCADE;
    
ALTER TABLE COMPRA_PRODUTOS ADD CONSTRAINT FK_COMPRA_PRODUTOS_2
    FOREIGN KEY (ID_COMPRA)
    REFERENCES COMPRA (NF)
    ON DELETE CASCADE;