/*iNSERIR*/
INSERT INTO USUARIO (ID, NOME, SENHA)
VALUES (1, 'CAIO_REIS', 0101);

INSERT INTO USUARIO (ID, NOME, SENHA)
VALUES (2, 'RENATA_GONDIM', 0202);

INSERT INTO USUARIO (ID, NOME, SENHA)
VALUES (3, 'LUCAS_VILARES', 0303);

INSERT INTO USUARIO (ID, NOME, SENHA)
VALUES (4, 'JOAO_RICARDO', 0404);

INSERT INTO USUARIO (ID, NOME, SENHA)
VALUES (5, 'ARIANE_ROCHA', 0505);

/*REMOVER*/
INSERT INTO USUARIO (ID, NOME, SENHA)
VALUES (6, 'DANIEL', 0606);

DELETE FROM USUARIO WHERE ID = 6;

/*MODIFICAR*/
INSERT INTO USUARIO VALUES (7,'ALEATORIO',0707);
UPDATE USUARIO SET ID = 10, NOME = 'ALGUEM MAIS ALAEATORIO', SENHA = 10013 WHERE ID = 7;

/*CONSULTAR*/
SELECT * FROM USUARIO;